-- MySQL Script generated by MySQL Workbench
-- Fri Nov 29 2024 20:00:00 GMT+0100 (CET)
-- Model: MiNuevoAmigo    Version: 1.0

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema minuevoamigo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `minuevoamigo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `minuevoamigo`;

-- -----------------------------------------------------
-- Table `minuevoamigo`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minuevoamigo`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `tipo` ENUM('adoptante', 'refugio') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `minuevoamigo`.`adoptantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minuevoamigo`.`adoptantes` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `ciudad` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_adoptantes_usuarios`
    FOREIGN KEY (`id`)
    REFERENCES `minuevoamigo`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `minuevoamigo`.`refugios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minuevoamigo`.`refugios` (
  `id` INT NOT NULL,
  `nombre_refugio` VARCHAR(200) NOT NULL,
  `nombre_contacto` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `direccion` TEXT NULL,
  `ciudad` VARCHAR(100) NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_refugios_usuarios`
    FOREIGN KEY (`id`)
    REFERENCES `minuevoamigo`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `minuevoamigo`.`animales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minuevoamigo`.`animales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo` ENUM('perro', 'gato', 'otro') NOT NULL,
  `edad_categoria` ENUM('cachorro', 'joven', 'adulto', 'mayor') NOT NULL,
  `sexo` ENUM('macho', 'hembra') NOT NULL,
  `raza` VARCHAR(100) NULL,
  `tamaño` ENUM('pequeño', 'mediano', 'grande') NOT NULL,
  `descripcion` TEXT NULL,
  `vacunado` TINYINT(1) NULL DEFAULT 0,
  `vacunas` TEXT NULL,
  `esterilizado` TINYINT(1) NULL DEFAULT 0,
  `nivel_energia` ENUM('bajo', 'medio', 'alto') NOT NULL,
  `relacion_niños` ENUM('excelente', 'buena', 'regular', 'mala') NOT NULL,
  `relacion_otros_animales` ENUM('excelente', 'buena', 'regular', 'mala') NOT NULL,
  `fecha_nacimiento` DATE NULL,
  `peso` DECIMAL(4,1) NULL,
  `necesidades_especiales` TEXT NULL,
  `id_refugio` INT NOT NULL,
  `estado` ENUM('disponible', 'adoptado', 'pendiente') NULL DEFAULT 'disponible',
  PRIMARY KEY (`id`),
  INDEX `fk_animales_usuarios_idx` (`id_refugio` ASC),
  CONSTRAINT `fk_animales_usuarios`
    FOREIGN KEY (`id_refugio`)
    REFERENCES `minuevoamigo`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `minuevoamigo`.`fotos_animales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minuevoamigo`.`fotos_animales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_animal` INT NOT NULL,
  `ruta_foto` VARCHAR(255) NOT NULL,
  `es_principal` TINYINT(1) NULL DEFAULT 0,
  `orden` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_fotos_animales_animales_idx` (`id_animal` ASC),
  CONSTRAINT `fk_fotos_animales_animales`
    FOREIGN KEY (`id_animal`)
    REFERENCES `minuevoamigo`.`animales` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `minuevoamigo`.`solicitudes_adopcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minuevoamigo`.`solicitudes_adopcion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_animal` INT NOT NULL,
  `id_adoptante` INT NOT NULL,
  `estado` ENUM('pendiente', 'aceptada', 'rechazada', 'cancelada') NULL DEFAULT 'pendiente',
  `fecha_solicitud` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_resolucion` TIMESTAMP NULL,
  `mensaje_adoptante` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_solicitudes_animales_idx` (`id_animal` ASC),
  INDEX `fk_solicitudes_usuarios_idx` (`id_adoptante` ASC),
  CONSTRAINT `fk_solicitudes_animales`
    FOREIGN KEY (`id_animal`)
    REFERENCES `minuevoamigo`.`animales` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_solicitudes_usuarios`
    FOREIGN KEY (`id_adoptante`)
    REFERENCES `minuevoamigo`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `minuevoamigo`.`usuarios`
-- (Datos de ejemplo opcionales)
-- -----------------------------------------------------
-- INSERT INTO `usuarios` (`username`, `email`, `password`, `tipo`) VALUES
-- ('admin', 'admin@minuevoamigo.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'refugio'),
-- ('mariagarcia', 'maria.garcia@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'adoptante');